---
title: "Data Analisis Sentimen Masyarakat Terhadap Kuliah Online"
author: "Juan Bontor Hutapea"
date: "2022-11-27"
output: html_document
---

```{r}
library(tm)
library(RTextTools)
library(dplyr)
library(wordcloud)
```

```{r}
df <- read.csv("tweet_kuliah_online.csv", stringsAsFactors = FALSE)
glimpse(df)

set.seed(20)
df <- df[sample(nrow(df)),]
df <- df[sample(nrow(df)),]
glimpse(df)

corpus <- Corpus(VectorSource(df$text))
corpus
inspect(corpus[1:10])

corpus.clean <- corpus %>%
  tm_map(content_transformer(tolower))%>%
  tm_map(removePunctuation)%>%
  tm_map(removeNumbers)%>%
  tm_map(removeWords,stopwords(kind="en"))%>%
  tm_map(stripWhitespace)
dtm <- DocumentTermMatrix(corpus.clean)

inspect(dtm[1:10, 1:20])

df.train <- df[1:100,]
df.test <- df[101:200,]

dtm.train <- dtm[1:100,]
dtm.test <- dtm[101:200,]

corpus.clean.train <- corpus.clean[1:100]
corpus.clean.test <- corpus.clean[101:200]

dim(dtm.train)
fivefreq <- findFreqTerms(dtm.train,5)
length(fivefreq)

dtm.train.nb <- DocumentTermMatrix(corpus.clean.train,control=list(dictionary=fivefreq))

dtm.test.nb <- DocumentTermMatrix(corpus.clean.test,control=list(dictionary=fivefreq))

dim(dtm.test.nb)

convert_count <- function(x){
  y <- ifelse(x > 0,1,0)
  y <- factor(y, levels=c(0,1), labels=c("no","yes"))
  y
}
trainNB <- apply(dtm.train.nb,2,convert_count)
testNB <- apply(dtm.test.nb,1,convert_count)

wordcloud(corpus.clean,min.freq=4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
```



