---
title:"Data Analisis Sentimen Masyarakat Terhadap Kuliah Online"
author: "Juan Bontor Hutapea"
date: "2022-11-27"
output: html_document
---

```{r}
library(wordcloud2)
library(shiny)
library(DT)
```


```{r}
twitter <- read.csv(file="tweet_kuliah_online.csv",header=TRUE)

tweet <- twitter$text

ui <- fluidPage(
  titlePanel("Tanggapan Masyarakat Terhadap Kuliah Online"), #halaman judul dr fluid page
  mainPanel( 
    #tab pada fluidpage
    #plot output : untuk Barplot
    tabsetPanel(type = "tabs",
                tabPanel("Data Twitter", DT::dataTableOutput('tbl')), #tab berupa data clening twitter
                tabPanel("Barplot", plotOutput("Barplot")), #tab berupa Barplot/grafik pada proses sebelumnya
                tabPanel("Wordcloud", plotOutput("Wordcloud")) #tab berupa worldcloud
    )
  )
)

# SERVER
# Disinialah tempat dimana data akan dianalisis dan diproses lalu hasilnya akan ditampilkan atau diplotkan pada bagian mainpanel() ui yang telah dijelaskan sebelumnya.
server <- function(input, output) {
  # Output Data
  output$tbl = DT::renderDataTable({ 
    DT::datatable(twitter, options = list(lengthChange = FALSE)) # data akan ditampilkan dalam beberapa halaman.
    })
  
  #Barplot
  output$Barplot <- renderPlot({tweetdata<-read.csv("tweet_kuliah_online.csv",stringsAsFactors = FALSE)
  tanggapan <-as.character(tweetdata$text)
  s<-get_nrc_sentiment(tanggapan)
  review_combine<-cbind(tweetdata$text,s)
  par(mar=rep(3,4))
  barplot(colSums(s),col=rainbow(10),ylab='count',main='Sentiment Analisis Tanggapan Masyarakat Terhadap Kuliah Online')
  }, height=400)
  
  #WordCloud
output$Wordcloud <- renderPlot({
  glimpse(df)
  set.seed(20)
  df <- df[sample(nrow(df)),]
  df <- df[sample(nrow(df)),]
  glimpse(df)

  corpus <- Corpus(VectorSource(df$text))
  corpus
  inspect(corpus[1:10])

  corpus.clean <- corpus %>%
    tm_map(content_transformer(tolower))%>%
    tm_map(removePunctuation)%>%
    tm_map(removeNumbers)%>%
    tm_map(removeWords,stopwords(kind="en"))%>%
    tm_map(stripWhitespace)
  dtm <- DocumentTermMatrix(corpus.clean)

  inspect(dtm[1:10, 1:20])

  df.train <- df[1:100,]
  df.test <- df[101:200,]

  dtm.train <- dtm[1:50,]
  dtm.test <- dtm[101:200,]

  corpus.clean.train <- corpus.clean[1:100]
  corpus.clean.test <- corpus.clean[101:200]

  dim(dtm.train)
  fivefreq <- findFreqTerms(dtm.train,5)
  length(fivefreq)

  dtm.train.nb <- DocumentTermMatrix(corpus.clean.train,control=list(dictionary=fivefreq))

  dtm.test.nb <- DocumentTermMatrix(corpus.clean.test,control=list(dictionary=fivefreq))

  dim(dtm.test.nb)

  convert_count <- function(x){
    y <- ifelse(x>0,1,0)
    y <- factor(y, levels=c(0,1), labels=c("no","yes"))
    y
  }
  trainNB <- apply(dtm.train.nb,2,convert_count)
  testNB <- apply(dtm.test.nb,1,convert_count)

  wordcloud(corpus.clean,min.freq=4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
  })
}
shinyApp(ui = ui, server = server)
```

